config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  devise_for :users

  resources :events, only: [:index, :show]
  resources :searches, only: [:create]

  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :location

  serialize :topics, Array

  validates :topics, array_contents: { contents: Enums::Topics::ALL }
  validates :title, presence: true
  validates :date, presence: true
  validates :start_at, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :end_at, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate :start_at_before_end_at

  after_create_commit { EventBroadcastWorker.perform_async self.id }

  private

  def start_at_before_end_at
    return true unless end_at && start_at

    if end_at < start_at
      errors.add(:end_at, I18n.t(:start_at_before_end_at))
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :events

  validates :city, presence: true
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user

  serialize :metadata, Hash

  validates :metadata, presence: true
  validates :user_id, presence: true

  def match_event?(event)
    Queries::Events::Index.new(metadata).find.include?(event)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :searches
end

app/models/validators/array_contents_validator.rb
class ArrayContentsValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, array)
    valid_contents = options[:contents]

    if array.any? { |value| !valid_contents.include?(value) }
      record.errors.add(attribute, get_error_message(record, attribute))
    end
  end

  def get_error_message(object, field)
    I18n.t("activerecord.errors.models.#{object.class.name.underscore}.attributes.#{field}.contents",
           default: 'is not a valid content')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  helper_method :search_params

  SEARCH_PARAMS = [:city, :topic, :start_date, :end_date, :start_at, :end_at].freeze

  def index
    @events = Queries::Events::Index.new(search_params).find
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def search_params
    params.permit(SEARCH_PARAMS)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def create
    @search = current_user.searches.build(search_params)

    if @search.save
      message = { notice: t('search.created') }
    else
      message = { alert: t('search.failed') }
    end

    redirect_to root_path(params: search_params[:metadata]), message
  end

  private

  def search_params
    params.permit(metadata: {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    case flash_type
      when 'success' then 'alert-success'
      when 'error'   then 'alert-danger'
      when 'alert'   then 'alert-warning'
      when 'notice'  then 'alert-info'
      else flash_type.to_s
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def search_compact_json_params
    compact(search_params).as_json
  end

  private

  def compact(hash)
    hash.delete_if { |k, v| v.blank? }
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
  def metadata_text_link(metadata)
    metadata.map { |key, value| "#{key}: #{value} ~" }
  end
end

app/views/events/_event.html.erb
<tr>
  <td><%= event.title %></td>
  <td><%= event.date %></td>
  <td>
    <%= "#{Time.at(event.start_at).utc.strftime("%H:%M")} -
        #{Time.at(event.end_at).utc.strftime("%H:%M")}" %>
  </td>
  <td><%= event.location.city %></td>
  <td><%= event.topics.join(', ') %></td>
</tr>

app/views/events/_search_form.html.erb
<div class='col-sm-10'>
  <div class='container-fluid'>
    <%= simple_form_for(:search, url: url, method: :get, html: { class: 'form-horizontal' }) do |f| %>
      <div class='row'>
        <%= f.error_notification %>

        <div class='col-sm-3'>
          <div class='form-inline'>
            <%= f.input 'City',
              collection: Location.pluck(:city),
              required: false,
              include_blank: true,
              selected: search[:city],
              input_html: { name: :city }
            %>

            <%= f.input 'Topics',
              collection: Enums::Topics::ALL,
              required: false,
              include_blank: true,
              selected: search[:topic],
              input_html: { name: :topic }
            %>
          </div>
        </div>
        <div class='col-sm-3'>
          <div class='form-inline'>
            <%= f.input :start_date,
              as: :string,
              required: false,
              include_blank: true,
              selected: search[:start_date],
              placeholder: '2017-08-30',
              input_html: { name: :start_date, value: search[:start_date] }
            %>

            <%= f.input :end_date,
              as: :string,
              required: false,
              include_blank: true,
              placeholder: '2018-05-23',
              input_html: { name: :end_date, value: search[:end_date] }
            %>
          </div>
        </div>
        <div class='col-sm-3'>
          <div class='form-inline'>
            <%= f.input :start_at,
              as: :string,
              required: false,
              include_blank: true,
              placeholder: '10:00',
              input_html: { name: :start_at, value: search[:start_at] }
            %>
            <br  />

            <%= f.input :end_at,
              as: :string,
              required: false,
              include_blank: true,
              placeholder: '14:00',
              input_html: { name: :end_at, value: search[:end_at] }
            %>
          </div>
        </div>

        <div class='col-sm-3'>
          <div class='form-inline'>
            <%= f.button :submit, 'Search', class: 'btn btn-primary btn-lg' %>

            <% unless search_params.empty? %>
              <%= link_to 'Save Search',
                          searches_path(metadata: search_compact_json_params),
                          method: :post,
                          data: { confirm: "Are you sure?" },
                          class: 'btn btn-info btn-lg',
                          id: 'save-search' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class='row'>
  <%= render partial: 'events/search_form',
             locals: { search: search_params, url: events_path } %>

  <div class='col-sm-8'>
    <h1>Events</h1>

    <div class='container-fluid'>
      <table class='table'>
        <thead>
          <tr>
            <th>Title</th>
            <th>Date</th>
            <th>Time</th>
            <th>Location</th>
            <th>Topics</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
          <%= render 'event', event: event %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <% if user_signed_in? %>
    <div id='secondary-content'>
      <%= render 'searches/search_channel' %>

      <%= render 'searches/searches', searches: current_user.searches %>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class='row'>
  <div class='col-sm-8'>
    <h3><%= @event.title %></h3>
    <p>
      <b>Date: </b>
      <%= @event.date %>
    </p>
    <p>
      <b>Time</b>
      <%= "#{Time.at(@event.start_at).utc.strftime("%H:%M")} -
      #{Time.at(@event.end_at).utc.strftime("%H:%M")}" %>
    </p>
    <p>
      <b>Location City</b>
      <%= @event.location.city %>
    </p>
    <p>
      <b>Topics</b>
      <%= @event.topics.join(', ') %>
    </p>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Events JL - copyright@</p>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class='navbar navbar-dark bg-inverse'>
  <%= link_to 'Events JL', root_path, class: 'navbar-brand' %>

  <div class='row pull-right'>
    <div class='collapse navbar-collapse navbar-right navbar-main-collapse'>
      <ul class='nav navbar-nav'>
        <% if user_signed_in? %>
          <li>
            <%= link_to t('sessions.edit_account'), edit_user_registration_path, class: 'page-scroll' %>
          </li>
          <li>
            <%= link_to t('sessions.sign_out'), destroy_user_session_path, method: 'delete', class: 'page-scroll' %>
          </li>
        <% else %>
          <li>
            <%= link_to t('sessions.sign_in'), new_user_session_path, class: 'page-scroll' %>
          </li>
          <li>
            <%= link_to t('sessions.sign_up'), new_user_registration_path, class: 'page-scroll' %>
          </li>
        <% end %>
      </ul>
    </div>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <%= render partial: 'layouts/flash_messages', flash: flash %>

    <div class='container-fluid'>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/searches/_new_match_search.erb
<li>
  <%= link_to event.title, event_path(event.id) %>
</li>

app/views/searches/_search.html.erb
<li class='list-group-item list-group-item-info'>
  <%= link_to metadata_text_link(search.metadata),
              events_path(search.metadata) %>
</li>

app/views/searches/_search_channel.html.erb
<div class='col-sm-4 bg-info search-channel'>
  <h3>Match Events with your search:</h3>

  <div id='search-channel'>
  </div>
</div>

app/views/searches/_searches.html.erb
<div class='col-sm-4 bg-info'>
  <h3>Your searches:</h3>

  <% if searches.any? %>
    <ul class='list-group'>
      <% searches.each do |search| %>
        <%= render 'searches/search', search: search %>
      <% end %>
    </ul>
  <% end %>
</div>